# Generated by Django 3.2.9 on 2021-11-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('location_from', models.CharField(max_length=200)),
                ('location_to', models.CharField(max_length=200)),
                ('pickup_time', models.TimeField()),
            ],
        ),
    ]
